### ISSUE TITLE
Request to improve software metadata for CLARIAH

### ISSUE THREAD

**Issue by proycon** [rug-compling/Alpino#12]
In CLARIAH we are automatically collecting software metadata for all tools in CLARIAH-PLUS (and CLARIAH-CORE). This metadata is automatically and periodically harvested directly from the source code repositories, and this Alpino git repo is one of those sources. The advantage of this approach is that metadata is as close to the source as possible, reflects the actual software version, and developers retain full authorship and control without needing any middlemen.

The results are published daily on https://tools.clariah.nl/ and this will in turn be queried by other platforms (Ineo, CLARIN VLO) to disseminate the tools in portals for end-users.

The harvesting is set-up in such a way that various existing metadata formats are supported and automatically converted. The whole idea is to burden developers as little as possible, use standards they already use, and prevent any unnecessary duplication of metadata fields. But Alpino is not currently using any scheme, so our harvester doesn't have much to fallback to, and as a consequence the metadata quality is rather poor.

In January a call went out to request all CLARIAH developers to take a look at this metadata and to improve upon it where needed (see https://github.com/CLARIAH/clariah-plus/issues/143). Alpino has a long history in CLARIAH and CLARIN and is much used, so we'd like to have good metadata for it. Could you take a look at improving the metadata? Alpino's results are currently [like this](https://tools.clariah.nl/alpino).

It would also help a lot if you could use github's release mechanism (i.e. git tags) to tag releases of Alpino (with a semantic version).

Please see the [contributing guidelines](https://github.com/CLARIAH/tool-discovery/blob/master/CONTRIBUTING.md) and the [CLARIAH Software Metadata Requirements](https://github.com/CLARIAH/clariah-plus/blob/main/requirements/software-metadata-requirements.md) for in-depth instructions on what metadata to provide and how this can be accomplished.

**Comment by gertjanvannoord** [comment]
tja, Alpino is geen Clariah of Clarin software... dus dit heeft geen
prioriteit vrees ik

**Comment by gertjanvannoord** [comment]
inmiddels is er een metadata bestand toegevoegd
